description: Prepare for CI jobs

name: Prepare
runs:
  steps:
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    - name: Install dependencies
      run: bun install
      shell: bash

  using: composite

