jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actions
        uses: actions/checkout@v3
      - name: Prepare actions
        uses: ./.github/actions/prepare
      - name: fmt 
        run: bun run ci
      - uses: mshick/add-pr-comment@v2
        if: failure()
        with:
          message-failure: |
            Uh oh! Biome found some issues. Please run `bun fmt` and commit the changes

name: Biome lint and format

on:
  pull_request: ~
  merge_group: ~

  push:
    branches:
      - main

