jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actions
        uses: actions/checkout@v3
      - name: Prepare actions
        uses: ./.github/actions/prepare
      - name: test
        run: bun run test
      - uses: mshick/add-pr-comment@v2
        if: failure()
        with:
          message-failure: |
            Uh oh! Some tests are broken. Please fix them and commit the changes

name: Bun Test

on:
  pull_request: ~
  merge_group: ~

  push:
    branches:
      - main

